analytics: {}
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.875
  lightness: 0.5
  rhythmicContrast: 0.75
  saturation: 0.8250570103991777
cta: {}
layout_spectrum: 0.538651
name: LC Media Consulting
opengraph: {}
purpose: []
typography_spectrum: 0.95775
