name: LC Media Consulting
favicon: null
layout_spectrum: 0.07163640088401735
typography_spectrum: 0.9169
title: LC Media Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.012663118774071336
  lightness: 0.40501510933972895
  saturation: 0.8250570103991777
  rhythmicContrast: 0.11863184534013271
purpose: []
